// user info
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const

// timelapse
export const FETCH_TIMELINE = 'FETCH_TIMELINE';

// chamber info
export const FETCH_CHAMBER_INFORMATION = 'FETCH_CHAMBER_INFORMATION';
export const UPDATE_CHAMBER_INFORMATION = 'UPDATE_CHAMBER_INFORMATION';
export const ARCHIVE_CHAMBER = 'ARCHIVE_CHAMBER'; //AFTER HARVEST DONE-- AKA DELETE CHAMBER

// plant info
export const FETCH_ALL_PLANT_INFORMATION = 'FETCH_ALL_PLANT_INFORMATION';
export const FETCH_PLANT_INFORMATION = 'FETCH_PLANT_INFORMATION';
export const ADD_PLANT = 'ADD_PLANT';


// IOT data
export const FETCH_ALL_CHAMBER_DATA = 'FETCH_ALL_CHAMBER_DATA';
export const FETCH_CHAMBER_SENSOR_DATA = 'FETCH_CHAMBER_SENSOR_DATA';


// notifications
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';


//
